# 01 — Explore the cached CFBD data

Loads every dataset from `data/raw/` and answers the questions that
shape the transfer dataset build in `src/build_dataset.py`. Findings are summarized
at the bottom.

In [1]:
import sys
from pathlib import Path

import pandas as pd

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT / "src"))
from build_dataset import load, normalize_name  # reuse the pipeline's loader

pd.set_option("display.max_columns", 50)
pd.set_option("display.width", 200)

NAMES = ["portal", "ppa", "usage", "stats", "recruiting", "teams_fbs"]
data = {name: load(name) for name in NAMES}
portal, ppa, usage, stats, rec, teams = (data[n] for n in NAMES)

## Overview of every dataset: shape, dtypes, missing values, sample rows

In [2]:
def overview(name, df, n=3):
    print(f"===== {name}: {df.shape[0]:,} rows x {df.shape[1]} cols "
          f"(years {df.pull_year.min()}-{df.pull_year.max()}) =====")
    summary = pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "missing": df.isna().sum(),
        "missing_pct": (df.isna().mean() * 100).round(1),
    })
    display(summary)
    display(df.head(n))

for name in NAMES:
    cols = [c for c in data[name].columns if not c.startswith("logos")]
    overview(name, data[name][cols])

===== portal: 14,422 rows x 11 cols (years 2021-2025) =====

                dtype  missing  missing_pct
season          int64        0          0.0
firstName      object        0          0.0
lastName       object        0          0.0
position       object        0          0.0
origin         object        0          0.0
destination    object     3971         27.5
transferDate   object        0          0.0
rating        float64     7802         54.1
stars         float64     1596         11.1
eligibility    object        0          0.0
pull_year       int64        0          0.0

   season firstName  lastName position          origin destination              transferDate  rating  stars eligibility  pull_year
0    2021   Cameron   Wilkins       LB        Missouri        UTSA  2021-07-31T14:46:00.000Z     NaN    3.0   Immediate       2021
1    2021     Javar    Strong        S  Arkansas State        None  2021-07-28T15:25:00.000Z     NaN    3.0   Immediate       2021
2    2021      Noah  Mitchell       LB            UTSA        None  2021-07-27T15:22:00.000Z     NaN    3.0   Immediate       2021

===== ppa: 25,579 rows x 23 cols (years 2020-2025) =====

                            dtype  missing  missing_pct
season                      int64        0          0.0
id                         object        0          0.0
name                       object        0          0.0
position                   object        0          0.0
team                       object        0          0.0
conference                 object        0          0.0
averagePPA.all            float64        0          0.0
averagePPA.pass           float64     2183          8.5
averagePPA.rush           float64    10501         41.1
averagePPA.firstDown      float64     2633         10.3
averagePPA.secondDown     float64     3003         11.7
averagePPA.thirdDown      float64     4609         18.0
averagePPA.standardDowns  float64     1307          5.1
averagePPA.passingDowns   float64     3035         11.9
totalPPA.all              float64        0          0.0
totalPPA.pass             float64        0          0.0
totalPPA.rush             float64        0          0.0
totalPPA.firstDown        float64        0          0.0
totalPPA.secondDown       float64        0          0.0
totalPPA.thirdDown        float64        0          0.0
totalPPA.standardDowns    float64        0          0.0
totalPPA.passingDowns     float64        0          0.0
pull_year                   int64        0          0.0

,season,id,name,position,team,conference,averagePPA.all,averagePPA.pass,averagePPA.rush,averagePPA.firstDown,averagePPA.secondDown,averagePPA.thirdDown,averagePPA.standardDowns,averagePPA.passingDowns,totalPPA.all,totalPPA.pass,totalPPA.rush,totalPPA.firstDown,totalPPA.secondDown,totalPPA.thirdDown,totalPPA.standardDowns,totalPPA.passingDowns,pull_year
0,2020,107494,Trey Sanders,RB,Alabama,SEC,-0.092,-0.843,-0.066,0.057,-0.260,-0.462,0.018,-0.441,-2.681,-0.843,-1.838,0.905,-3.124,-0.462,0.406,-3.087,2020
1,2020,3682406,Daniel Imatorbhebhe,TE,Illinois,B1G,1.484,1.484,NaN,1.502,NaN,1.449,1.502,1.449,4.452,4.452,0.000,3.003,0.000,1.449,3.003,1.449,2020
2,2020,3707332,Dahu Green,WR,Arkansas State,SBC,0.992,0.992,NaN,0.666,1.675,0.092,0.855,1.248,45.621,45.621,0.000,13.315,23.446,0.740,25.658,19.963,2020

===== usage: 25,579 rows x 15 cols (years 2020-2025) =====

                       dtype  missing  missing_pct
season                 int64        0          0.0
id                    object        0          0.0
name                  object        0          0.0
position              object        0          0.0
team                  object        0          0.0
conference            object        0          0.0
usage.overall        float64        0          0.0
usage.pass           float64        0          0.0
usage.rush           float64        0          0.0
usage.firstDown      float64        0          0.0
usage.secondDown     float64        0          0.0
usage.thirdDown      float64        0          0.0
usage.standardDowns  float64        0          0.0
usage.passingDowns   float64        0          0.0
pull_year              int64        0          0.0

,season,id,name,position,team,conference,usage.overall,usage.pass,usage.rush,usage.firstDown,usage.secondDown,usage.thirdDown,usage.standardDowns,usage.passingDowns,pull_year
0,2020,107494,Trey Sanders,RB,Alabama,SEC,0.108,0.008,0.207,0.118,0.146,0.020,0.109,0.104,2020
1,2020,3682406,Daniel Imatorbhebhe,TE,Illinois,B1G,0.023,0.054,0.000,0.033,0.000,0.038,0.023,0.024,2020
2,2020,3707332,Dahu Green,WR,Arkansas State,SBC,0.099,0.159,0.000,0.099,0.092,0.085,0.099,0.098,2020

===== stats: 730,337 rows x 10 cols (years 2020-2025) =====

             dtype  missing  missing_pct
season       int64        0          0.0
playerId    object        0          0.0
player      object        0          0.0
position    object        0          0.0
team        object        0          0.0
conference  object        0          0.0
category    object        0          0.0
statType    object        0          0.0
stat        object        0          0.0
pull_year    int64        0          0.0

   season playerId        player position     team conference   category statType stat  pull_year
0    2020   107494  Trey Sanders       RB  Alabama        SEC  defensive       PD    0       2020
1    2020   107494  Trey Sanders       RB  Alabama        SEC  defensive   QB HUR    0       2020
2    2020   107494  Trey Sanders       RB  Alabama        SEC  defensive    SACKS    0       2020

===== recruiting: 24,254 rows x 20 cols (years 2020-2025) =====

                          dtype  missing  missing_pct
id                       object        0          0.0
athleteId                object     8070         33.3
recruitType              object        0          0.0
year                      int64        0          0.0
ranking                 float64     3412         14.1
name                     object        0          0.0
school                   object        0          0.0
committedTo              object     3869         16.0
position                 object        0          0.0
height                  float64       28          0.1
weight                  float64       40          0.2
stars                   float64     3410         14.1
rating                  float64     3410         14.1
city                     object        3          0.0
stateProvince            object      147          0.6
country                  object       65          0.3
hometownInfo.latitude   float64      478          2.0
hometownInfo.longitude  float64      478          2.0
hometownInfo.fipsCode    object      478          2.0
pull_year                 int64        0          0.0

,id,athleteId,recruitType,year,ranking,name,school,committedTo,position,height,weight,stars,rating,city,stateProvince,country,hometownInfo.latitude,hometownInfo.longitude,hometownInfo.fipsCode,pull_year
0,118408,4428988,HighSchool,2020,1.0,Bryan Bresee,Damascus,Clemson,DT,77.0,290.0,5.0,0.9995,Damascus,MD,USA,39.288438,-77.203872,24031,2020
1,254348,4686250,HighSchool,2020,1.0,Alante Brown,St. Thomas More (Prep),Nebraska,WR,72.0,190.0,4.0,0.8937,Oakdale,CT,USA,41.466209,-72.157301,09011,2020
2,118409,None,HighSchool,2020,2.0,Bryce Young,Mater Dei,Alabama,DUAL,71.0,183.0,5.0,0.9994,Santa Ana,CA,USA,33.749495,-117.873221,06059,2020

===== teams_fbs: 792 rows x 26 cols (years 2020-2025) =====

                             dtype  missing  missing_pct
id                           int64        0          0.0
school                      object        0          0.0
mascot                      object        0          0.0
abbreviation                object        0          0.0
alternateNames              object        0          0.0
conference                  object        0          0.0
division                    object      453         57.2
classification              object        0          0.0
color                       object        0          0.0
alternateColor              object        0          0.0
twitter                     object        6          0.8
location.id                  int64        0          0.0
location.name               object        0          0.0
location.city               object        0          0.0
location.state              object        0          0.0
location.zip                object        0          0.0
location.countryCode        object        0          0.0
location.timezone           object        0          0.0
location.latitude          float64        0          0.0
location.longitude         float64        0          0.0
location.elevation          object        0          0.0
location.capacity            int64        0          0.0
location.constructionYear    int64        0          0.0
location.grass                bool        0          0.0
location.dome                 bool        0          0.0
pull_year                    int64        0          0.0

,id,school,mascot,abbreviation,alternateNames,conference,division,classification,color,alternateColor,twitter,location.id,location.name,location.city,location.state,location.zip,location.countryCode,location.timezone,location.latitude,location.longitude,location.elevation,location.capacity,location.constructionYear,location.grass,location.dome,pull_year
0,2005,Air Force,Falcons,AF,"[AF, Air Force]",Mountain West,None,fbs,#003594,#ffffff,@AF_Football,3713,Falcon Stadium,Colorado Springs,CO,80840,US,America/Denver,38.996970,-104.843616,2024.875732,46692,1962,False,False,2020
1,2006,Akron,Zips,AKR,"[AKR, Akron]",Mid-American,East,fbs,#041e42,#a89968,@ZipsFB,3768,InfoCision Stadium,Akron,OH,44399,US,America/New_York,41.072553,-81.508341,321.2875061,30000,2009,False,False,2020
2,333,Alabama,Crimson Tide,ALA,"[ALA, Alabama]",SEC,West,fbs,#9e1b32,#ffffff,@AlabamaFTBL,3657,Bryant-Denny Stadium,Tuscaloosa,AL,35487,US,America/Chicago,33.208275,-87.550384,70.05136108,101821,1929,True,False,2020

## What does the portal `season` field mean?

Two checks: (1) when do transfer dates fall relative to `season`, and (2) which team
do well-known transfers appear with in the production data for that season.

In [3]:
print("season always equals the file's pull year:", (portal.season == portal.pull_year).all())
months = portal.assign(month=portal.transferDate.str[:7])
display(months.groupby("season").month.agg(["min", "max"]))

season always equals the file's pull year: True

            min      max
season
2021    2020-08  2021-07
2022    2021-08  2022-09
2023    2020-11  2023-07
2024    2022-12  2024-05
2025    2024-10  2025-08

In [4]:
KNOWN = [("Caleb", "Downs"), ("Cameron", "Ward"), ("Cam", "Ward"), ("Michael", "Penix Jr."),
         ("Bo", "Nix"), ("Jayden", "Daniels"), ("Will", "Howard")]
prod = stats[["season", "playerId", "player", "team"]].drop_duplicates()
for first, last in KNOWN:
    p = portal[(portal.firstName == first) & (portal.lastName == last)]
    if p.empty:
        continue
    print(f"\n## {first} {last}")
    display(p[["season", "origin", "destination", "transferDate"]])
    display(prod[prod.player.map(normalize_name).str.endswith(normalize_name(last))
                 & prod.player.str.startswith(first[:3])].sort_values("season"))

## Caleb Downs

      season   origin destination              transferDate
7899    2024  Alabama  Ohio State  2024-01-17T15:39:00.000Z

        season playerId       player        team
402831    2023  4870706  Caleb Downs     Alabama
509567    2024  4870706  Caleb Downs  Ohio State
617629    2025  4870706  Caleb Downs  Ohio State

## Cameron Ward

      season          origin       destination              transferDate
3896    2022  Incarnate Word  Washington State  2021-12-11T01:00:00.000Z

        season playerId        player              team
166611    2021  4688380  Cameron Ward    Incarnate Word
269554    2022  4688380  Cameron Ward  Washington State
380657    2023  4688380  Cameron Ward  Washington State
489786    2024  4688380  Cameron Ward             Miami

## Cam Ward

      season            origin destination              transferDate
7537    2024  Washington State       Miami  2024-01-14T01:26:00.000Z

        season playerId        player              team
166611    2021  4688380  Cameron Ward    Incarnate Word
269554    2022  4688380  Cameron Ward  Washington State
380657    2023  4688380  Cameron Ward  Washington State
489786    2024  4688380  Cameron Ward             Miami

## Michael Penix Jr.

      season   origin destination              transferDate
3437    2022  Indiana  Washington  2021-12-06T01:15:00.000Z

        season playerId             player        team
26625     2020  4360423  Michael Penix Jr.     Indiana
101024    2021  4360423  Michael Penix Jr.     Indiana
194964    2022  4360423  Michael Penix Jr.  Washington
322820    2023  4360423  Michael Penix Jr.  Washington

## Bo Nix

      season  origin destination              transferDate
3117    2022  Auburn      Oregon  2021-12-13T20:53:00.000Z

        season playerId  player    team
58106     2020  4567218  Bo Nix  Auburn
143645    2021  4567218  Bo Nix  Auburn
215060    2022  4426338  Bo Nix  Oregon
333149    2023  4426338  Bo Nix  Oregon

## Jayden Daniels

      season         origin destination              transferDate
2084    2022  Arizona State         LSU  2022-02-17T18:35:00.000Z

        season playerId          player           team
43322     2020  4426348  Jayden Daniels  Arizona State
122343    2021  4426348  Jayden Daniels  Arizona State
215135    2022  4426348  Jayden Daniels            LSU
333192    2023  4426348  Jayden Daniels            LSU

## Will Howard

      season        origin destination              transferDate
8397    2024  Kansas State  Ohio State  2023-11-27T22:06:00.000Z

        season playerId       player          team
52669     2020  4429955  Will Howard  Kansas State
134213    2021  4429955  Will Howard  Kansas State
227440    2022  4429955  Will Howard  Kansas State
343777    2023  4429955  Will Howard  Kansas State
461095    2024  4429955  Will Howard    Ohio State

**Result:** `season` is the **first season the player plays at the new school**. Transfer
dates for season *S* run from fall *S-1* through summer *S*. Caleb Downs (2024) shows up
for Alabama in 2023 and Ohio State in 2024. Cam Ward (2024; listed as "Cameron Ward" in
stats) shows up for Washington State in 2023 and Miami in 2024. So BEFORE = origin in
*S-1* and AFTER = destination in *S*.

## Missing destinations and repeated players

In [5]:
nodest = portal.destination.isna()
print(f"No destination: {nodest.sum():,} of {len(portal):,} ({nodest.mean():.1%})")
display(portal.assign(no_dest=nodest).groupby("season").no_dest.agg(["sum", "mean"]))
display(pd.crosstab(portal.eligibility.fillna("NA"), nodest.rename("no_destination")))
print("destination == origin (returned to same school):", (portal.destination == portal.origin).sum())

No destination: 3,971 of 14,422 (27.5%)

        sum      mean
season
2021    717  0.405085
2022    906  0.398592
2023    895  0.357714
2024    724  0.214328
2025    729  0.162036

no_destination  False  True
eligibility
Immediate        9891   3182
PendingAppeal      12      3
SittingOne          1      3
TBD               545    529
Withdrawn           2    254

destination == origin (returned to same school): 142

In [6]:
portal["name_norm"] = (portal.firstName + " " + portal.lastName).map(normalize_name)
seasons_per_name = portal.groupby("name_norm").season.nunique()
print("names in the portal in more than one season:", (seasons_per_name > 1).sum())

same_cycle = portal[portal.duplicated(["season", "name_norm", "origin"], keep=False)]
print("rows sharing season + name + origin (same player listed twice in one cycle):", len(same_cycle))
display(same_cycle.sort_values(["season", "name_norm"])[
    ["season", "firstName", "lastName", "position", "origin", "destination", "transferDate", "stars"]])

print("rows sharing season + name with DIFFERENT origins (mostly common names):",
      portal.duplicated(["season", "name_norm"], keep=False).sum()
      - portal.duplicated(["season", "name_norm", "origin"], keep=False).sum())

# Example of a genuine multi-transfer player.
display(portal[portal.name_norm == "dillon gabriel"][["season", "origin", "destination"]])

names in the portal in more than one season: 1900
rows sharing season + name + origin (same player listed twice in one cycle): 14

       season firstName    lastName position          origin        destination              transferDate  stars
1772     2022    Isaiah     Johnson       CB       Dartmouth           Syracuse  2022-02-07T16:48:00.000Z    NaN
2226     2022    Isaiah     Johnson       CB       Dartmouth           Syracuse  2021-12-06T20:53:00.000Z    3.0
2176     2022    Tyrone       Brown       LB          Baylor               None  2021-09-07T13:46:00.000Z    3.0
2398     2022    Tyrone       Brown        S          Baylor               None  2021-09-08T02:05:00.000Z    3.0
4845     2023     Sione       Finau      IOL          Purdue      Arizona State  2023-03-30T14:18:00.000Z    3.0
5357     2023     Sione       Finau       RB          Purdue               None  2023-03-30T20:55:00.000Z    3.0
6610     2024     Dylan     Barrett      IOL       Wisconsin         Iowa State  2023-11-29T06:00:00.000Z    3.0
6669     2024     Dylan     Barrett      IOL       Wisconsin         Iowa State  2023-12-04T15:45:00.000Z    3.0
6801     2024      Fred  Norman Jr.       OT          Furman               None  2024-03-25T05:00:00.000Z    3.0
7918     2024      Fred      Norman       OT          Furman               None  2024-03-25T20:38:00.000Z    NaN
6682     2024     Jovon     Jackson        S  Fairmont State               None  2023-11-20T21:51:00.000Z    NaN
9616     2024     Jovon     Jackson        S  Fairmont State         Texas Tech  2023-11-21T05:54:00.000Z    3.0
10882    2025     Alvin  Gulley Jr.       DL            Yale  Northern Illinois  2024-11-26T20:41:00.000Z    NaN
11427    2025     Alvin  Gulley Jr.       DL            Yale               None  2024-11-25T20:45:00.000Z    2.0

rows sharing season + name with DIFFERENT origins (mostly common names): 124

      season    origin destination
2635    2022       UCF    Oklahoma
6655    2024  Oklahoma      Oregon

## PPA and usage structure

In [7]:
print("PPA columns:", [c for c in ppa.columns])
print("Usage columns:", [c for c in usage.columns])
print("\nPPA positions:", ppa.position.value_counts().to_dict())

PPA columns: ['season', 'id', 'name', 'position', 'team', 'conference', 'averagePPA.all', 'averagePPA.pass', 'averagePPA.rush', 'averagePPA.firstDown', 'averagePPA.secondDown', 'averagePPA.thirdDown', 'averagePPA.standardDowns', 'averagePPA.passingDowns', 'totalPPA.all', 'totalPPA.pass', 'totalPPA.rush', 'totalPPA.firstDown', 'totalPPA.secondDown', 'totalPPA.thirdDown', 'totalPPA.standardDowns', 'totalPPA.passingDowns', 'pull_year']
Usage columns: ['season', 'id', 'name', 'position', 'team', 'conference', 'usage.overall', 'usage.pass', 'usage.rush', 'usage.firstDown', 'usage.secondDown', 'usage.thirdDown', 'usage.standardDowns', 'usage.passingDowns', 'pull_year']

PPA positions: {'WR': 10625, 'RB': 6851, 'TE': 4010, 'QB': 3969, 'FB': 124}

In [8]:
dups = ppa[ppa.duplicated(["season", "id"], keep=False)]
differing = [c for c in ppa.columns
             if dups.groupby(["season", "id"])[c].nunique(dropna=False).max() > 1]
print(f"PPA rows sharing season+id: {len(dups):,}; columns that differ within them: {differing}")
display(dups.sort_values(["season", "id"])[["season", "id", "name", "team", "conference", "totalPPA.all"]].head(4))
print("usage rows sharing season+id:", usage.duplicated(["season", "id"], keep=False).sum())

value_cols = [c for c in ppa.columns if c.startswith(("totalPPA", "averagePPA"))]
n_vals = dups.groupby(["season", "id", "team"])["totalPPA.all"].nunique()
print(f"blank-conference repeats: {(n_vals == 1).sum()} | split across positions: {(n_vals > 1).sum()}")
display(dups[(dups.id == "4677280") & (dups.season == 2022)][["season", "name", "team", "position", "totalPPA.all", "averagePPA.all"]])

PPA rows sharing season+id: 706; columns that differ within them: ['position', 'conference', 'averagePPA.all', 'averagePPA.pass', 'averagePPA.rush', 'averagePPA.firstDown', 'averagePPA.secondDown', 'averagePPA.thirdDown', 'averagePPA.standardDowns', 'averagePPA.passingDowns', 'totalPPA.all', 'totalPPA.pass', 'totalPPA.rush', 'totalPPA.firstDown', 'totalPPA.secondDown', 'totalPPA.thirdDown', 'totalPPA.standardDowns', 'totalPPA.passingDowns']

     season       id           name       team conference  totalPPA.all
61     2020  4035387  Reginald Todd       Troy        SBC        29.669
62     2020  4035387  Reginald Todd       Troy                   29.669
212    2020  4039467   Tre Harbison  Charlotte       CUSA         9.564
213    2020  4039467   Tre Harbison  Charlotte                    9.564

usage rows sharing season+id: 706
blank-conference repeats: 283 | split across positions: 70

      season         name      team position  totalPPA.all  averagePPA.all
8473    2022  Julian Gray  NC State       RB         4.543           0.413
8474    2022  Julian Gray  NC State       WR         7.429           0.825

PPA is nested JSON: `averagePPA` and `totalPPA` each split into all / pass / rush /
firstDown / secondDown / thirdDown / standardDowns / passingDowns, which `json_normalize`
flattens to `averagePPA.all`, `totalPPA.pass`, etc. Usage has the same split under
`usage.*` (with `overall` instead of `all`). **Both cover only offensive skill players**
(QB/RB/WR/TE/FB).

The 353 duplicated player-team-seasons come in two kinds: 283 are exact repeats
except for a blank `conference` (drop one), and **70 are players CFBD split across
two positions** (e.g. RB and WR) with their PPA divided between the rows. Those
have to be **combined**: sum the totals and recompute averages from implied plays.

## Stats: long or wide?

In [9]:
print("rows per player-team-season:")
display(stats.groupby(["season", "playerId", "team"]).size().describe())
display(stats[stats.player == "Caleb Downs"].head(10))
display(stats.groupby("category").statType.unique().to_frame())
print("stat column dtype:", stats.stat.dtype, "| sample values:", stats.stat.unique()[:8])
print("players with >1 team in a season:",
      (stats.groupby(["season", "playerId"]).team.nunique() > 1).sum())

rows per player-team-season:

count    75983.000000
mean         9.611847
std          4.884156
min          3.000000
25%          7.000000
50%          7.000000
75%         12.000000
max         40.000000
dtype: float64

        season playerId       player position     team conference   category statType stat  pull_year
402831    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive       PD    3       2023
402832    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive   QB HUR    0       2023
402833    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive    SACKS    0       2023
402834    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive     SOLO   70       2023
402835    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive       TD    1       2023
402836    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive      TFL  3.5       2023
402837    2023  4870706  Caleb Downs        S  Alabama        SEC  defensive      TOT  107       2023
402838    2023  4870706  Caleb Downs        S  Alabama        SEC    fumbles      FUM    0       2023
402839    2023  4870706  Caleb Downs        S  Alabama        SEC    fumbles     LOST    0       2023
402840    2023  4870706  Caleb Downs        S  Alabama        SEC    fumbles      REC    1       2023

                                                 statType
category
defensive         [PD, QB HUR, SACKS, SOLO, TD, TFL, TOT]
fumbles                                  [FUM, LOST, REC]
interceptions                         [AVG, INT, TD, YDS]
kickReturns                      [AVG, LONG, NO, TD, YDS]
kicking              [FGA, FGM, LONG, PCT, PTS, XPA, XPM]
passing        [ATT, COMPLETIONS, INT, PCT, TD, YDS, YPA]
puntReturns                      [AVG, LONG, NO, TD, YDS]
punting                   [In 20, LONG, NO, TB, YDS, YPP]
receiving                       [LONG, REC, TD, YDS, YPR]
rushing                         [CAR, LONG, TD, YDS, YPC]

stat column dtype: object | sample values: ['0' '1' '17.0' '17' '-2' '-2.0' '29' '25']

players with >1 team in a season: 23

Stats are **long format**: one row per player × team × season × (category, statType),
with `stat` stored as a **string**. It has to be converted to numbers and pivoted wide.
It covers all positions, but only players who recorded at least one stat.

## ID fields and links between datasets

In [10]:
id_fields = {
    "portal": "(none)", "ppa": "id", "usage": "id", "stats": "playerId",
    "recruiting": "id (recruit), athleteId", "teams_fbs": "id (team)",
}
display(pd.Series(id_fields, name="id fields"))

key = lambda df, col: set(zip(df.season, df[col].astype(str)))
print("ppa (season,id) found in usage:", f"{len(key(ppa,'id') & key(usage,'id')) / len(key(ppa,'id')):.1%}")
stat_ids = set(stats.playerId.astype(str))
print("ppa id found in stats playerId:", f"{ppa.id.astype(str).isin(stat_ids).mean():.1%}")
print("recruiting athleteId found in stats playerId:", f"{rec.athleteId.astype(str).isin(stat_ids).mean():.1%}")

portal                         (none)
ppa                                id
usage                              id
stats                        playerId
recruiting    id (recruit), athleteId
teams_fbs                   id (team)
Name: id fields, dtype: object

ppa (season,id) found in usage: 100.0%
ppa id found in stats playerId: 99.6%

recruiting athleteId found in stats playerId: 42.7%

In [11]:
# Does an athlete's ID survive a transfer?
for name in ["Cameron Ward", "Caleb Downs", "Bo Nix"]:
    display(stats[stats.player == name][["season", "playerId", "player", "team"]].drop_duplicates())

        season playerId        player              team
166611    2021  4688380  Cameron Ward    Incarnate Word
269554    2022  4688380  Cameron Ward  Washington State
380657    2023  4688380  Cameron Ward  Washington State
489786    2024  4688380  Cameron Ward             Miami

        season playerId       player        team
402831    2023  4870706  Caleb Downs     Alabama
509567    2024  4870706  Caleb Downs  Ohio State
617629    2025  4870706  Caleb Downs  Ohio State

        season playerId  player    team
58106     2020  4567218  Bo Nix  Auburn
143645    2021  4567218  Bo Nix  Auburn
215060    2022  4426338  Bo Nix  Oregon
333149    2023  4426338  Bo Nix  Oregon

PPA `id` = usage `id` = stats `playerId` (the CFBD athlete ID). It usually stays the
same through a transfer (Cam Ward, Caleb Downs), but **not always**: Bo Nix has
different IDs at Auburn and Oregon. The portal has **no player ID**, so portal rows have
to be matched by name + team + season. Recruiting `athleteId` links to stats for ~43% of
recruits (many never record a stat).

## Team name spelling across datasets

In [12]:
fbs_all = set(teams.school)
display(teams.groupby("pull_year").school.nunique().rename("FBS teams"))
for label, s in [("portal origin", portal.origin), ("portal destination", portal.destination),
                 ("ppa", ppa.team), ("usage", usage.team), ("stats", stats.team),
                 ("recruiting committedTo", rec.committedTo)]:
    names = set(s.dropna())
    print(f"{label:24} {len(names):4} names | FBS names used: {len(names & fbs_all):3} "
          f"| FBS names never used: {sorted(fbs_all - names)[:5]}")

pull_year
2020    128
2021    130
2022    131
2023    133
2024    134
2025    136
Name: FBS teams, dtype: int64

portal origin             394 names | FBS names used: 136 | FBS names never used: []
portal destination        422 names | FBS names used: 134 | FBS names never used: ['Army', 'Navy']
ppa                       312 names | FBS names used: 136 | FBS names never used: []
usage                     312 names | FBS names used: 136 | FBS names never used: []

stats                     330 names | FBS names used: 136 | FBS names never used: []
recruiting committedTo    265 names | FBS names used: 136 | FBS names never used: []

In [13]:
import difflib
# Non-FBS names that look like an FBS spelling variant
all_names = set(portal.origin) | set(portal.destination.dropna()) | set(stats.team) | set(ppa.team)
near = {n: difflib.get_close_matches(n, fbs_all, 1, 0.85) for n in all_names - fbs_all}
display({k: v for k, v in near.items() if v})
display(teams.drop_duplicates("school")[teams.drop_duplicates("school").school.isin(
    ["Miami", "Miami (OH)", "UConn", "Hawai'i", "San José State", "App State", "UL Monroe"])][
    ["school", "alternateNames"]])
print("conference labels -- ppa:", sorted(ppa.conference.dropna().unique())[:8],
      "| stats:", sorted(stats.conference.dropna().unique())[:8])

{'Eastern Kentucky': ['Western Kentucky'],
 'Southern Illinois': ['Northern Illinois'],
 'Bowie State': ['Boise State'],
 'North Carolina A&T': ['North Carolina'],
 'SE Louisiana': ['Louisiana']}

             school                       alternateNames
3         App State  [Appalachian State, APP, App State]
37          Hawai'i                       [HAW, Hawai'i]
56            Miami             [Miami (FL), MIA, Miami]
57       Miami (OH)                     [M-OH, Miami OH]
88   San José State    [San Jose St., SJSU, San José St]
110       UL Monroe         [La.-Monroe, ULM, UL Monroe]
239           UConn           [Connecticut, CONN, UConn]

conference labels -- ppa: ['', 'AAC', 'ACC', 'ASUN', 'AWC', 'B12', 'B1G', 'BSKY'] | stats: ['ACC', 'AWC', 'American Athletic', 'Atlantic Sun', 'Big 12', 'Big Sky', 'Big South', 'Big South-OVC']

Team names are **consistent**: every FBS school name in `teams_fbs` appears verbatim in
portal, PPA, usage and stats, and the only near-misses (Bowie State vs Boise State, etc.)
are different schools. Non-FBS names are FCS/D2 programs. Conference labels are *not*
consistent (PPA uses `B1G`, stats uses `Big Ten`), but they aren't used for joining.

## Summary of findings

| Question | Finding | Consequence for the build |
|---|---|---|
| Portal `season` | First season at the **new** school (Downs: Alabama 2023 → Ohio State 2024; Ward: WSU 2023 → Miami 2024) | BEFORE = origin, season−1; AFTER = destination, season |
| No destination | 3,971 of 14,422 (27.5%); includes all 256 "Withdrawn" rows | Dropped by the FBS-destination filter |
| destination == origin | 142 rows (player returned to the same school) | Dropped as a separate, logged step (configurable) |
| Repeat players | ~1,900 normalized names appear in more than one portal season (real repeat transfers like Dillon Gabriel 2022 and 2024) | Each portal entry is its own transfer row |
| Same-cycle duplicates | 7 pairs share season + name + origin; most have one null destination | Exact repeats deduped (keep latest) |
| PPA / usage | Nested `averagePPA` / `totalPPA` / `usage` dicts flattened to `x.all`, `x.pass`, `x.rush`, down splits. **Offense only** (QB/RB/WR/TE/FB). 353 duplicated keys: 283 blank-conference repeats, 70 players split across two positions | Repeats dropped, splits combined; defenders/OL get no PPA |
| Stats | **Long** format, `stat` stored as a string, all positions, only players who recorded a stat | Converted to numbers, key stats pivoted wide |
| IDs | Portal has none. PPA `id` = usage `id` = stats `playerId`. Usually stable across a transfer but not always (Bo Nix). Recruiting `athleteId` links to stats for ~43% | Match by name; use ID only to link the other side |
| Team names | Consistent across all datasets for FBS schools (Army and Navy never appear as a portal destination); conference labels differ | Join directly on team name |

**Survivorship caveat:** production data only includes players with at least one
recorded stat. OL, long snappers and players who never got on the field will have
no AFTER match even when the name is right. That is real signal, not a matching failure.